### PR TITLE
Testing tweaks

### PR DESCRIPTION
**Pull request by joharohl**
Just did some changes that makes it easier for _me_ to run tests. Hope it is worth merging as well :)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/wg-manager/21)

### CODE REVIEW

**Review by Rizzly — APPROVED** [review]
Very nice! :+1:

**Comment by ret394** [comment]
why u kids trust wireguard? well, if all of u do it, then it must be anti-privacy tool.

It's always the opposite with the mob. Good people are called criminals and tried in the US court. And bad people are h

**Comment by jbjorkang** [comment]
> why u kids trust wireguard? well, if all of u do it, then it must be anti-privacy tool.
> 
> It's always the opposite with the mob. Good people are called criminals and tried in the US court. And bad people are h

Thanks for your feedback. Since this is off-topic and not related to this PR I will have to hide your comment.

If you have concerns about our usage of Wireguard, please do not hesitate to contact us via the email listed on our website: https://www.mullvad.net/

**Comment by ret394** [comment]
https://github.com/jbjorkang

thanks, but why don't u minimise ur comment as well, its high noise.

And when r u going to comment on the 30 things wrong with this PR? is this run by the CIA to snoop on Swedish sheeple.

---
ref -sheeple, for example - @jborkang

**Pull request closed without merging**
